# Generated by Django 4.2.18 on 2025-03-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usedpassword',
            name='user',
        ),
        migrations.AlterField(
            model_name='usedpassword',
            name='hashed_password',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
